apiVersion: v1
kind: PersistentVolume
metadata:
  name: oc-lab-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: skills-network-learner
  hostPath:
    path: /mnt/data/oc-lab-pv
